version: '3'
services:

  nginx-entrypoint:
    image: 'nginx:latest'
    restart: always
    volumes:
      - './nginx-entrypoint.conf:/etc/nginx/nginx.conf:ro'
    networks:
      - new
    ports:
      - '80:80'
    depends_on:
      - nginx-vue-a
      - nginx-vue-b
      - nginx-python-a
      - nginx-python-b
      - php

  nginx-vue-a:
    image: 'nginx:latest'
    restart: always
    volumes:
      - './nginx-vue.conf:/etc/nginx/nginx.conf:ro'
      - ./code:/code
    networks:
      - new

  nginx-vue-b:
    image: 'nginx:latest'
    restart: always
    volumes:
      - './nginx-vue.conf:/etc/nginx/nginx.conf:ro'
      - ./code:/code
    networks:
      - new

  nginx-python-a:
    image: 'nginx:latest'
    restart: always
    volumes:
      - './nginx-vue.conf:/etc/nginx/nginx.conf:ro'
      - ./code:/code
    networks:
      - new

  nginx-python-b:
    image: 'nginx:latest'
    restart: always
    volumes:
      - './nginx-vue.conf:/etc/nginx/nginx.conf:ro'
      - ./code:/code
    networks:
      - new

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
    networks:
      - new

networks:
  new:
    driver: bridge
